# version: '3'
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./.env.docker
    depends_on:
      - postgres

  postgres:
    image : postgres:15
    environment:
      - POSTGRES_PASSWORD=41321234
      - POSTGRES_DB=fastapi
    ports:
      - "5433:5432"
    volumes :
      - postgres_db:/var/lib/postgresql/data

volumes :
  postgres_db: