# version: '3'
services:
  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env.docker
    depends_on:
      - postgres

  postgres:
    image : postgres:15
    environment:
      - POSTGRES_PASSWORD=41321234
      - POSTGRES_DB=FASTAPI
    volumes :
      - postgres_db:/var/lib/postgresql/data

volumes :
  postgres_db: